
networks:

services:
  backend:
    build:
      dockerfile: Dockerfile.backend
      ports: 
        - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      ports: 
        - "3000:3000"
    restart: unless-stopped

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
