FROM alpine:latest
RUN apk update && apk add alpine-sdk neovim git ripgrep nodejs npm openssh zsh shadow curl tmux go
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

WORKDIR /root
RUN mkdir .config/

RUN chsh -s $(which zsh)
COPY ./containers/.zshrc ./.zshrc
COPY . ./platy
